#! /bin/bash

for i in `seq 1 60`; do 
sudo mkdir /srv/nfs/pv$i;
done;

cat << EOF >> /etc/exports.d/hw-mounts
"/srv/nfs/pv1" *(rw,root_squash)
"/srv/nfs/pv2" *(rw,root_squash)
"/srv/nfs/pv3" *(rw,root_squash)
"/srv/nfs/pv4" *(rw,root_squash)
"/srv/nfs/pv5" *(rw,root_squash)
"/srv/nfs/pv6" *(rw,root_squash)
"/srv/nfs/pv7" *(rw,root_squash)
"/srv/nfs/pv8" *(rw,root_squash)
"/srv/nfs/pv9" *(rw,root_squash)
"/srv/nfs/pv10" *(rw,root_squash)
"/srv/nfs/pv11" *(rw,root_squash)
"/srv/nfs/pv12" *(rw,root_squash)
"/srv/nfs/pv13" *(rw,root_squash)
"/srv/nfs/pv14" *(rw,root_squash)
"/srv/nfs/pv15" *(rw,root_squash)
"/srv/nfs/pv16" *(rw,root_squash)
"/srv/nfs/pv17" *(rw,root_squash)
"/srv/nfs/pv18" *(rw,root_squash)
"/srv/nfs/pv19" *(rw,root_squash)
"/srv/nfs/pv20" *(rw,root_squash)
"/srv/nfs/pv21" *(rw,root_squash)
"/srv/nfs/pv22" *(rw,root_squash)
"/srv/nfs/pv23" *(rw,root_squash)
"/srv/nfs/pv24" *(rw,root_squash)
"/srv/nfs/pv25" *(rw,root_squash)
"/srv/nfs/pv26" *(rw,root_squash)
"/srv/nfs/pv27" *(rw,root_squash)
"/srv/nfs/pv28" *(rw,root_squash)
"/srv/nfs/pv29" *(rw,root_squash)
"/srv/nfs/pv30" *(rw,root_squash)
"/srv/nfs/pv31" *(rw,root_squash)
"/srv/nfs/pv32" *(rw,root_squash)
"/srv/nfs/pv33" *(rw,root_squash)
"/srv/nfs/pv34" *(rw,root_squash)
"/srv/nfs/pv35" *(rw,root_squash)
"/srv/nfs/pv36" *(rw,root_squash)
"/srv/nfs/pv37" *(rw,root_squash)
"/srv/nfs/pv38" *(rw,root_squash)
"/srv/nfs/pv39" *(rw,root_squash)
"/srv/nfs/pv40" *(rw,root_squash)
"/srv/nfs/pv41" *(rw,root_squash)
"/srv/nfs/pv42" *(rw,root_squash)
"/srv/nfs/pv43" *(rw,root_squash)
"/srv/nfs/pv44" *(rw,root_squash)
"/srv/nfs/pv45" *(rw,root_squash)
"/srv/nfs/pv46" *(rw,root_squash)
"/srv/nfs/pv47" *(rw,root_squash)
"/srv/nfs/pv48" *(rw,root_squash)
"/srv/nfs/pv49" *(rw,root_squash)
"/srv/nfs/pv50" *(rw,root_squash)
"/srv/nfs/pv51" *(rw,root_squash)
"/srv/nfs/pv52" *(rw,root_squash)
"/srv/nfs/pv53" *(rw,root_squash)
"/srv/nfs/pv54" *(rw,root_squash)
"/srv/nfs/pv55" *(rw,root_squash)
"/srv/nfs/pv56" *(rw,root_squash)
"/srv/nfs/pv57" *(rw,root_squash)
"/srv/nfs/pv58" *(rw,root_squash)
"/srv/nfs/pv59" *(rw,root_squash)
"/srv/nfs/pv60" *(rw,root_squash)
EOF

sudo chown -R nfsnobody. /srv/nfs/pv*;
sudo chmod -R 777 /srv/nfs/pv*;
sudo exportfs -r
